"""Initial schema

Revision ID: bc374c7d93a2
Revises: 
Create Date: 2025-11-07 20:34:36.347159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc374c7d93a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csi_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csi_codes_code'), 'csi_codes', ['code'], unique=True)
    op.create_index(op.f('ix_csi_codes_division'), 'csi_codes', ['division'], unique=False)
    op.create_index(op.f('ix_csi_codes_id'), 'csi_codes', ['id'], unique=False)
    op.create_table('icc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'year', 'state', name='uix_code_year_state')
    )
    op.create_index(op.f('ix_icc_documents_code'), 'icc_documents', ['code'], unique=False)
    op.create_index(op.f('ix_icc_documents_id'), 'icc_documents', ['id'], unique=False)
    op.create_index(op.f('ix_icc_documents_state'), 'icc_documents', ['state'], unique=False)
    op.create_index(op.f('ix_icc_documents_year'), 'icc_documents', ['year'], unique=False)
    op.create_table('icc_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['icc_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icc_sections_chapter'), 'icc_sections', ['chapter'], unique=False)
    op.create_index(op.f('ix_icc_sections_id'), 'icc_sections', ['id'], unique=False)
    op.create_index(op.f('ix_icc_sections_section_number'), 'icc_sections', ['section_number'], unique=False)
    op.create_table('csi_icc_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csi_code_id', sa.Integer(), nullable=False),
    sa.Column('icc_section_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['csi_code_id'], ['csi_codes.id'], ),
    sa.ForeignKeyConstraint(['icc_section_id'], ['icc_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csi_code_id', 'icc_section_id', name='uix_csi_icc')
    )
    op.create_index(op.f('ix_csi_icc_mappings_id'), 'csi_icc_mappings', ['id'], unique=False)
    op.create_table('state_amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icc_section_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('amendment_text', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['icc_section_id'], ['icc_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_amendments_id'), 'state_amendments', ['id'], unique=False)
    op.create_index(op.f('ix_state_amendments_state'), 'state_amendments', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_amendments_state'), table_name='state_amendments')
    op.drop_index(op.f('ix_state_amendments_id'), table_name='state_amendments')
    op.drop_table('state_amendments')
    op.drop_index(op.f('ix_csi_icc_mappings_id'), table_name='csi_icc_mappings')
    op.drop_table('csi_icc_mappings')
    op.drop_index(op.f('ix_icc_sections_section_number'), table_name='icc_sections')
    op.drop_index(op.f('ix_icc_sections_id'), table_name='icc_sections')
    op.drop_index(op.f('ix_icc_sections_chapter'), table_name='icc_sections')
    op.drop_table('icc_sections')
    op.drop_index(op.f('ix_icc_documents_year'), table_name='icc_documents')
    op.drop_index(op.f('ix_icc_documents_state'), table_name='icc_documents')
    op.drop_index(op.f('ix_icc_documents_id'), table_name='icc_documents')
    op.drop_index(op.f('ix_icc_documents_code'), table_name='icc_documents')
    op.drop_table('icc_documents')
    op.drop_index(op.f('ix_csi_codes_id'), table_name='csi_codes')
    op.drop_index(op.f('ix_csi_codes_division'), table_name='csi_codes')
    op.drop_index(op.f('ix_csi_codes_code'), table_name='csi_codes')
    op.drop_table('csi_codes')
    # ### end Alembic commands ###
